ignore:
    - "jambot/charts.py"
    - "jambot/tradesys/strategies/chop.py"
    - "jambot/tradesys/strategies/sfp.py"
    - "jambot/tradesys/strategies/trend.py"
    - "jambot/tradesys/strategies/trendclose.py"
    - "jambot/tradesys/strategies/trendrev.py"
    - "jambot/utils/styles.py"