ETHUSD:
  thing: 5
XBTUSD:
  boosting_type: dart
  filter_fit_quantile: 0.7
  learning_rate: 0.1
  max_depth: 40
  n_estimators: 100
  n_periods_smooth: 5
  num_feats: 36
  num_leaves: 100
  random_state: 0
  target_n_periods: 26
